$ErrorActionPreference = 'Stop'
$cli = 'C:\Users\Administrator\.codex\skills\gpt-image-2-skill\scripts\gpt_image_2_skill.cjs'
$node = 'C:\Users\Administrator\.cache\codex-runtimes\codex-primary-runtime\dependencies\node\bin\node.exe'
$tmp = 'E:\codex\Game\tmp\imagegen\v16_combo_vfx'
New-Item -ItemType Directory -Force -Path $tmp | Out-Null

$jobs = @(
  @{ id='piercing_star_burst'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for the piercing star projectile combo. All panels aligned to one center and separated by very thin empty gutters. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. Cyan-white star-shaped armor-piercing projectile strikes, punches through, ignites a compact orange-hot core, emits sharp cyan radial fragments and a short shockwave, then fades. Each panel only contains the effect on a completely flat solid pure magenta #ff00ff background. No text, labels, UI, border, terrain, enemy, character, smoke gradient, soft glow, anti-aliasing or extra objects. Consistent silhouette, center and light source in every panel.' }
  @{ id='hunt_barrage_lock'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for a hunter barrage target-lock combo effect. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. A cyan pixel targeting lattice snaps around a target point, creates two or three angular ricochet nodes, flashes a yellow-white lock spark, then collapses into tiny cyan fragments. Every panel is centered and aligned on a flat solid pure magenta #ff00ff background. No text, labels, UI, border, terrain, enemy, character, soft glow, gradient, anti-aliasing or extra objects. Keep the lock readable at 64 pixels.' }
  @{ id='zero_storm_burst'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for a zero-distance storm shotgun combo. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. A compact cyan-white radial shotgun blast expands from the center into layered pellet spokes, adds a few orange hot muzzle nodes, reaches a broad ring of hard pixel fragments and fades. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, enemy, character, soft glow, gradient or anti-aliasing. Keep all panels centered and consistent.' }
  @{ id='sword_wave'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for a warrior rift slash sword-wave combo. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. A broad cyan-white crescent blade tears forward from a compact orange-red sword core, produces two secondary stepped blade waves, peaks with a sharp rift edge, then breaks into square sparks. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, enemy, character, soft glow, gradient or anti-aliasing. One centered directional slash in every panel.' }
  @{ id='star_ring'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for a warrior star ring sword-array combo. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. Orange-gold circular ring and cyan-white orbiting pixel blades assemble around one center, rotate through a strong pulse, flare into a crisp cutting halo, then settle to a smaller ring. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, enemy, character, soft glow, gradient or anti-aliasing. Keep ring center and radius stable.' }
  @{ id='phantom_counter'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for a warrior phantom counter combo. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. A compact acid-green dodge afterimage splits into two angular phantom silhouettes, snaps into an orange counter spark, releases a cyan-white cross slash and a short all-direction shock ring, then fades. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, enemy, character, soft glow, gradient or anti-aliasing. Keep the center fixed and the silhouette crisp.' }
  @{ id='swarm_protocol'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for a mechanic swarm protocol combo. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. Three to five acid-green drone silhouettes deploy around a cyan core, connect with branching electric arcs, form a tight hexagonal swarm lattice, pulse once, then scatter into square sparks. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, enemy, character, soft glow, gradient or anti-aliasing. Keep the center fixed and readable at 96 pixels.' }
  @{ id='mobile_fortress'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for a mechanic mobile fortress combo. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. Acid-green shield plates and cyan turret nodes unfold around a central core, lock into a compact armored ring, emit two short turret pulses, then retract into a bright mechanical outline. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, enemy, character, soft glow, gradient or anti-aliasing. Keep the center and radius stable.' }
  @{ id='recycle_burst'; prompt='A clean 4 by 2 storyboard sheet containing exactly eight sequential animation panels for a mechanic infinite recycle protocol combo. Hard-edged medium-detail 8-bit pixel art for a vertical mobile sci-fi roguelite. A cyan repair core breaks into acid-green mechanical fragments, forms a compact self-destruct burst, then reconstructs a bright circular repair chassis with small orange warning sparks before fading. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, enemy, character, soft glow, gradient or anti-aliasing. Keep the effect centered with generous margin.' }
)

foreach ($job in $jobs) {
  $out = Join-Path $tmp ($job.id + '_source.png')
  if (Test-Path -LiteralPath $out) {
    Write-Host ("SKIP " + $job.id + " (source exists)")
    continue
  }
  Write-Host ("GENERATE " + $job.id)
  & $node $cli --json --json-events --provider codex images generate --prompt $job.prompt --out $out --format png --size 2K --quality medium
  if ($LASTEXITCODE -ne 0 -or !(Test-Path -LiteralPath $out)) {
    throw ("GPT-Image 2 generation failed for " + $job.id)
  }
}
Write-Host 'V16 storyboard generation complete.'
