$ErrorActionPreference = 'Stop'
$node = 'C:\Users\Administrator\.cache\codex-runtimes\codex-primary-runtime\dependencies\node\bin\node.exe'
$cli = 'C:\Users\Administrator\.codex\skills\gpt-image-2-skill\scripts\gpt_image_2_skill.cjs'
$tmp = 'E:\codex\Game\tmp\imagegen\v10_planet_props'
New-Item -ItemType Directory -Force -Path $tmp | Out-Null

$jobs = @(
  @{ id='rust_scrap_plate'; planet='rust'; ref='E:\codex\Game\assets\game\props\rust\objects\scrap_plate.png'; prompt='Use the supplied reference only for the subject silhouette and identity. Redraw a single isolated oxidized scrap metal plate as a production game prop on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Match the established medium-detail hard-edged 8-bit pixel style of the Rust Wasteland map: dark graphite outline, rust-red and brown oxidized metal blocks, a few sharp orange corrosion highlights, tiny pixel chips, and a compact hard-edged contact shadow. One centered 32x32-style object with generous magenta margin. No text, UI, scene, terrain, border, gradient, soft glow, or extra objects, and no magenta inside the subject.' }
  @{ id='rust_cable_coil'; planet='rust'; ref='E:\codex\Game\assets\game\props\rust\objects\cable_coil.png'; prompt='Use the supplied reference only for the subject silhouette and identity. Redraw a single isolated coiled industrial cable as a production game prop on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Match the established hard-edged 8-bit Rust Wasteland style: black-brown cable loops, oxidized copper clamps, rust-red accents, a few orange exposed wire pixels, and a compact hard-edged contact shadow. One centered 32x32-style object with generous magenta margin. No text, UI, scene, terrain, border, gradient, soft glow, or extra objects, and no magenta inside the subject.' }
  @{ id='rust_pipe_junction'; planet='rust'; ref='E:\codex\Game\assets\game\props\rust\objects\pipe_junction.png'; prompt='Use the supplied reference only for the subject silhouette and identity. Redraw a single isolated industrial pipe junction as a production game prop on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Match the established hard-edged 8-bit Rust Wasteland style: three chunky oxidized pipes, dark graphite seams, rust-red metal plates, pale orange rim highlights and a compact hard-edged contact shadow. One centered 64x64-style object with generous magenta margin. No text, UI, scene, terrain, border, gradient, soft glow, or extra objects, and no magenta inside the subject.' }
  @{ id='rust_power_pylon'; planet='rust'; ref='E:\codex\Game\assets\game\props\rust\objects\power_pylon.png'; prompt='Use the supplied reference only for the subject silhouette and identity. Redraw a single isolated damaged power pylon as a production game prop on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Match the established hard-edged 8-bit Rust Wasteland style: narrow dark metal tower, rust-red brackets, a few orange warning lamps, exposed cable pixels and a compact hard-edged contact shadow. One centered 64x64-style object with generous magenta margin. No text, UI, scene, terrain, border, gradient, soft glow, or extra objects, and no magenta inside the subject.' }
  @{ id='rust_scorch_mark'; planet='rust'; ref='E:\codex\Game\assets\game\props\rust\decals\scorch_mark.png'; prompt='Use the supplied reference only for the decal silhouette. Redraw a single isolated scorched blast mark ground decal on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged 8-bit pixels matching the Rust Wasteland surface: irregular charcoal burn patches, rust-orange ember flecks and broken square edges. Flat decal only, centered in a 64x64-style canvas. No cast shadow, no scene, no terrain tile, no border, no text, no gradient, no soft glow, and no magenta inside the decal.' }
  @{ id='rust_oil_stain'; planet='rust'; ref='E:\codex\Game\assets\game\props\rust\decals\oil_stain.png'; prompt='Use the supplied reference only for the decal silhouette. Redraw a single isolated oily mechanical spill ground decal on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged 8-bit pixels matching the Rust Wasteland surface: irregular near-black brown stain, broken rust-red edge pixels and a few dull orange reflections. Flat decal only, centered in a 64x64-style canvas. No cast shadow, no scene, no terrain tile, no border, no text, no gradient, no soft glow, and no magenta inside the decal.' }
  @{ id='rust_metal_seam'; planet='rust'; ref='E:\codex\Game\assets\game\props\rust\decals\metal_seam.png'; prompt='Use the supplied reference only for the decal silhouette. Redraw a single isolated broken metal floor seam ground decal on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged 8-bit pixels matching the Rust Wasteland surface: one irregular dark graphite seam with stepped rust-red plate edges and a few tiny orange corrosion nodes. Flat decal only, centered in a 64x64-style canvas. No cast shadow, no scene, no terrain tile, no border, no text, no gradient, no soft glow, and no magenta inside the decal.' }
  @{ id='rust_cable_run'; planet='rust'; ref='E:\codex\Game\assets\game\props\rust\decals\cable_run.png'; prompt='Use the supplied reference only for the decal silhouette. Redraw a single isolated broken cable run ground decal on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged 8-bit pixels matching the Rust Wasteland surface: a dark cable line with two or three square bends, rust-red clamps and tiny orange contact points. Flat decal only, centered in a 64x64-style canvas. No cast shadow, no scene, no terrain tile, no border, no text, no gradient, no soft glow, and no magenta inside the decal.' }
  @{ id='spore_spore_pod_cluster'; planet='spore'; prompt='Create a single isolated alien spore pod cluster game prop on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged medium-detail 8-bit pixel art matching the established Spore Swamp map style: three to five low bulbous pods with deep violet skin, dark green seams, tiny acid-lime bioluminescent pores and a compact hard-edged contact shadow. One centered 32x32-style object with generous magenta margin. No text, UI, scene, terrain, border, gradient, soft glow, or extra objects, and no magenta inside the subject.' }
  @{ id='spore_mycelium_stump'; planet='spore'; prompt='Create a single isolated alien mycelium stump game prop on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged medium-detail 8-bit pixel art matching the established Spore Swamp map style: short stepped fungal stalk, dark green-black base, layered purple cap, a few acid-lime spore dots and a compact hard-edged contact shadow. One centered 32x32-style object with generous magenta margin. No text, UI, scene, terrain, border, gradient, soft glow, or extra objects, and no magenta inside the subject.' }
  @{ id='spore_fungal_mound'; planet='spore'; prompt='Create a single isolated broad fungal mound game prop on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged medium-detail 8-bit pixel art matching the established Spore Swamp map style: layered dark green organic mound, violet mycelium shelves, purple contour blocks, small acid-lime luminous pores and a compact hard-edged contact shadow. One centered 64x64-style object with generous magenta margin. No text, UI, scene, terrain, border, gradient, soft glow, or extra objects, and no magenta inside the subject.' }
  @{ id='spore_husk_remains'; planet='spore'; prompt='Create a single isolated alien husk remains game prop on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged medium-detail 8-bit pixel art matching the established Spore Swamp map style: collapsed insectoid shell plates, dark olive and violet organic armor, a few purple fungal threads, tiny acid-lime residue pixels and a compact hard-edged contact shadow. One centered 64x64-style object with generous magenta margin. No text, UI, scene, terrain, border, gradient, soft glow, or extra objects, and no magenta inside the subject.' }
  @{ id='spore_spore_pool_decal'; planet='spore'; prompt='Create a single isolated alien spore pool ground decal on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged 8-bit pixel art matching the established Spore Swamp surface: irregular dark purple pool, deep green inner islands, a few acid-lime bubbles and broken violet rim pixels. Flat decal only, centered in a 64x64-style canvas. No cast shadow, no scene, no terrain tile, no border, no text, no gradient, no soft glow, and no magenta inside the decal.' }
  @{ id='spore_mycelium_rift'; planet='spore'; prompt='Create a single isolated branching mycelium rift ground decal on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged 8-bit pixel art matching the established Spore Swamp surface: dark green-black organic fissure, branching violet mycelium edges and a few dim acid-lime nodes. Flat decal only, centered in a 64x64-style canvas. No cast shadow, no scene, no terrain tile, no border, no text, no gradient, no soft glow, and no magenta inside the decal.' }
  @{ id='spore_acid_stain'; planet='spore'; prompt='Create a single isolated acidic corrosion stain ground decal on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged 8-bit pixel art matching the established Spore Swamp surface: uneven dark violet and olive stain, broken acid-lime edge pixels, tiny bubbles and sparse cyan-green glints. Flat decal only, centered in a 64x64-style canvas. No cast shadow, no scene, no terrain tile, no border, no text, no gradient, no soft glow, and no magenta inside the decal.' }
  @{ id='spore_root_trail'; planet='spore'; prompt='Create a single isolated branching alien root trail ground decal on a completely flat solid pure magenta #ff00ff background for later chroma-key extraction. Hard-edged 8-bit pixel art matching the established Spore Swamp surface: several irregular dark green root lines, violet mycelium tips, a few dim acid-lime nodes and broken square ends. Flat decal only, centered in a 64x64-style canvas. No cast shadow, no scene, no terrain tile, no border, no text, no gradient, no soft glow, and no magenta inside the decal.' }
)

foreach ($job in $jobs) {
  $out = Join-Path $tmp ($job.id + '_master.png')
  $args = @('--json','--json-events','--provider','codex','images')
  if ($job.ref) {
    $args += @('edit','--prompt',$job.prompt,'--out',$out,'--format','png','--size','2K','--quality','medium','--ref-image',$job.ref)
  } else {
    $args += @('generate','--prompt',$job.prompt,'--out',$out,'--format','png','--size','2K','--quality','medium')
  }
  Write-Output ("START " + $job.id)
  & $node $cli @args
  if ($LASTEXITCODE -ne 0) { throw ("GPT-Image 2 failed for " + $job.id) }
  if (!(Test-Path -LiteralPath $out)) { throw ("Missing generated output for " + $job.id) }
  Write-Output ("DONE " + $job.id)
}
