$ErrorActionPreference = 'Stop'
$cli = 'C:\Users\Administrator\.codex\skills\gpt-image-2-skill\scripts\gpt_image_2_skill.cjs'
$node = 'C:\Users\Administrator\.cache\codex-runtimes\codex-primary-runtime\dependencies\node\bin\node.exe'
$tmp = 'E:\codex\Game\tmp\imagegen\v19_combo_vfx'
New-Item -ItemType Directory -Force -Path $tmp | Out-Null

$jobs = @(
  @{ id='burst_overdrive'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a gunner burst overdrive combo VFX. Hard-edged medium-detail 8-bit pixel art matching an existing vertical sci-fi roguelite: cyan-white triple-shot streams converge, three muzzle pulse nodes stack into a focused barrage, a small acid-green overclock spark appears, the concentrated volley peaks, then breaks into square cyan fragments and fades. Every panel shares one fixed center, stable scale and light source. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, bullets as separate objects, smoke, gradients, soft glow or anti-aliasing.' }
  @{ id='railgun_overcharge'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a gunner railgun overcharge combo VFX. Hard-edged medium-detail 8-bit pixel art matching a vertical sci-fi roguelite: compact orange charge core grows inside a cyan-white rail channel, segmented energy bars lock into one perfectly straight beam, one single centered piercing flash fires, then the channel cools into small pixels. Fixed center and stable scale in every panel. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, duplicate beams, parallel rays, gradient, soft glow or anti-aliasing.' }
  @{ id='critical_dash'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a gunner critical dash combo VFX. Hard-edged medium-detail 8-bit pixel art matching a vertical sci-fi roguelite: short cyan-white propulsion streak, acid-green directional lock brackets, a compact orange critical spark, a sharp forward hit flash, then a few pixel afterimages fade. Keep one centered event origin and consistent silhouette across all panels. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, smoke, gradient, soft glow or anti-aliasing.' }
  @{ id='fury_combo'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a warrior fury combo VFX. Hard-edged medium-detail 8-bit pixel art matching an existing 8-bit sci-fi roguelite: two cyan-white sword arcs cross into an orange-red X, the overlapping slash grows into a broad stepped double cut, warm yellow impact pixels peak, then the crossed arcs fragment and fade. Fixed center, directional melee silhouette, stable scale. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, gradients, soft glow or anti-aliasing.' }
  @{ id='iron_fury'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a warrior iron fury combo VFX. Hard-edged medium-detail 8-bit pixel art matching an existing 8-bit sci-fi roguelite: a compact oblique cyan-white shield ring assembles, orange-red guard sparks strike its rim, a warm yellow counter pulse pushes outward, then the ring contracts into small armor pixels. Use a flattened斜俯视 elliptical shield perspective, fixed center and stable scale. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, gradients, soft glow or anti-aliasing.' }
  @{ id='blood_oath'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a warrior blood oath combo VFX. Hard-edged medium-detail 8-bit pixel art matching an existing 8-bit sci-fi roguelite: a dark crimson life pulse contracts toward a cyan-white center, orange recovery shards orbit inward, a short warm red-gold sealing flash appears, then the pulse settles into a small heartbeat pixel and fades. Fixed center, clean readable silhouette. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, gradients, soft glow or anti-aliasing.' }
  @{ id='parallel_overclock'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a mechanic parallel overclock combo VFX. Hard-edged medium-detail 8-bit pixel art matching an existing 8-bit sci-fi roguelite: four acid-green mechanical nodes appear around a cyan core, electric-blue arcs connect them, the network overclocks into a bright angular lattice, then discharges into a few square sparks. Fixed center and radius in every panel. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, gradients, soft glow or anti-aliasing.' }
  @{ id='field_reconstruction'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a mechanic field reconstruction combo VFX. Hard-edged medium-detail 8-bit pixel art matching an existing 8-bit sci-fi roguelite: small cyan repair nodes deploy from four directions, acid-green mechanical plates assemble into a compact cross-shaped repair pulse, white-cyan rings expand once, then the parts settle and fade. Fixed center and stable scale. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, gradients, soft glow or anti-aliasing.' }
  @{ id='magnetic_reclaim'; prompt='A clean 4 by 2 storyboard sheet with exactly eight sequential panels for a mechanic magnetic reclaim combo VFX. Hard-edged medium-detail 8-bit pixel art matching an existing 8-bit sci-fi roguelite: acid-green and rust-silver scrap pixels form a broken outer magnetic ring, cyan-white magnetic lines pull every fragment inward, a bright recovery core pulses once, then the ring dissolves into tiny square particles. Fixed center, stable radius and clear silhouette. Flat solid pure magenta #ff00ff background only. No text, labels, UI, border, terrain, character, enemy, gradients, soft glow or anti-aliasing.' }
)

foreach ($job in $jobs) {
  $out = Join-Path $tmp ($job.id + '_source.png')
  if (Test-Path -LiteralPath $out) {
    Write-Host ("SKIP " + $job.id + " (source exists)")
    continue
  }
  Write-Host ("GENERATE " + $job.id)
  & $node $cli --json --json-events --provider codex images generate --prompt $job.prompt --out $out --format png --size 2K --quality medium
  if ($LASTEXITCODE -ne 0 -or !(Test-Path -LiteralPath $out)) {
    throw ("GPT-Image 2 generation failed for " + $job.id)
  }
}
Write-Host 'V19 storyboard generation complete.'
